#pragma kernel CSMain

// 車の構造体
struct Car
{
	float3 size;
	float4 col;
	float2 pos;
	float2 dir;
	float velocity;
};

// 前回の更新からの経過時間
float DeltaTime;

// 車の構造化バッファ
RWStructuredBuffer<Car> Cars;

// (8, 1, 1)のスレッドで回す
[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	// 現在位置で回転し続ける
    float sina, cosa;
    sincos(0.02, sina, cosa);
    float2x2 _matrix = float2x2(cosa, -sina, sina, cosa);
    float2 dir = Cars[id.x].dir;
    Cars[id.x].dir =  mul(dir, _matrix);
}